[workspace]
members = ["visusta",
    "visusta-core",
    "visusta-cpu",
    "visusta-gpu",
]
resolver = "3"

[workspace.dependencies]
anyhow = "1.0.100"
image = { version = "0.25.8", features = ["rayon", "serde"] }
libm = "0.2.15"
rayon = "1.11.0"
log = "0.4.29"
