[package]
name = "visusta-cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
visusta-core = { version = "0.1.0", path = "../visusta-core" }
log.workspace = true
image.workspace = true
async-trait = "0.1.89"
rayon.workspace = true
