[package]
name = "visusta-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
image.workspace = true
visusta-core = { version = "0.1.0", path = "../visusta-core" }
visusta-cpu = { version = "0.1.0", path = "../visusta-cpu" }
wgpu = "27.0.1"
